<a href="https://colab.research.google.com/github/Arkaprabha1012/pythonopencv/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
#value
t1=torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
#vector
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [5]:
#matrix
t3=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [6]:
#3 dimensional array
t4=torch.tensor([[[11,12,23],[89,43,78]],[[15,16,12],[54,65,76]]])
t4

tensor([[[11, 12, 23],
         [89, 43, 78]],

        [[15, 16, 12],
         [54, 65, 76]]])

In [7]:
#value
t1.shape

torch.Size([])

In [8]:
#array
t2.shape

torch.Size([4])

In [9]:
#matrix
t3.shape

torch.Size([4, 2])

In [10]:
#3d matrix
t4.shape

torch.Size([2, 2, 3])

In [11]:
##TENSOR OPERATIONS AND GRADIENTS

In [12]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [13]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [14]:
#computer derivatives
y.backward()

In [15]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [16]:
#WITH NUMPY,MATPLOTLIB,OPENCV,PANDAS

In [17]:
import numpy as np
x=np.array([[1,2],[3.,4]])
x

array([[1., 2.],
       [3., 4.]])

In [18]:
#Creating torch tensor from numpy
y=torch.tensor(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [19]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [20]:
#Tensor to numpy
z=y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [21]:
import jovian

In [22]:
jovian.commit()

[jovian] Detected Colab notebook...


[jovian] Error: jovian.commit doesn't work on Colab unless the notebook was created and executed from Jovian.
Make sure to run the first code cell at the top after executing from Jovian.
Alternatively, you can download this notebook and upload it manually to Jovian.
Learn more: https://jovian.ai/docs/user-guide/run.html#run-on-colab
