<a href="https://colab.research.google.com/github/Arkaprabha1012/pythonopencv/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [119]:
import torch

In [120]:
#value
t1=torch.tensor(4.)
t1

tensor(4.)

In [121]:
t1.dtype

torch.float32

In [122]:
#vector
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [123]:
#matrix
t3=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [124]:
#3 dimensional array
t4=torch.tensor([[[11,12,23],[89,43,78]],[[15,16,12],[54,65,76]]])
t4

tensor([[[11, 12, 23],
         [89, 43, 78]],

        [[15, 16, 12],
         [54, 65, 76]]])

In [125]:
#value
t1.shape

torch.Size([])

In [126]:
#array
t2.shape

torch.Size([4])

In [127]:
#matrix
t3.shape

torch.Size([4, 2])

In [128]:
#3d matrix
t4.shape

torch.Size([2, 2, 3])

In [129]:
##TENSOR OPERATIONS AND GRADIENTS

In [130]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [131]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [132]:
#computer derivatives
y.backward()

In [133]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [134]:
#WITH NUMPY,MATPLOTLIB,OPENCV,PANDAS

In [135]:
import numpy as np
x=np.array([[1,2],[3.,4]])
x

array([[1., 2.],
       [3., 4.]])

In [136]:
#Creating torch tensor from numpy
y=torch.tensor(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [137]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [138]:
#Tensor to numpy
z=y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [139]:
import numpy as np
import torch

In [140]:
#input temp raifall humidity
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')
#input taget variables (apples,oranges)
targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

In [141]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs,"\n",targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### **LINEAR REGRESSION USING GRADIENT DESCENT**

yield_apple=w11*temp+w12*rainfall+w13*humidity+b1

yield_orange=w21*temp+w22*rainfall+w23*humidity+b2

In [142]:
w=torch.randn(2,3,requires_grad=True)#WE HAVE THREE INPUT AND TWO TARGETS
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.2023, -1.6035,  0.0601],
        [ 1.9144, -0.7120, -0.2854]], requires_grad=True)
tensor([-0.4001, -1.0923], requires_grad=True)


X  x WT(Transpos of W) + b

In [143]:
def model(x):
  return x @ w.t() + b
#@ means matrix multiplication in PYTORCH .t is for transpos

In [144]:
preds=model(inputs)
preds

tensor([[ -90.4818,   78.6806],
        [-119.2514,   92.1938],
        [-194.1846,   53.4946],
        [ -46.4900,  152.9996],
        [-136.1702,   42.6683]], grad_fn=<AddBackward0>)

In [145]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


LOSS FUNCTION

In [146]:
#MSE(Mean Squared Error) LOSS 
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [147]:
loss=mse(preds,targets)
print(loss)

tensor(24729.1855, grad_fn=<DivBackward0>)


### COMPUTE GRADIENTS

In [148]:
loss.backward()

In [149]:
print(w)
print(w.grad)

tensor([[ 0.2023, -1.6035,  0.0601],
        [ 1.9144, -0.7120, -0.2854]], requires_grad=True)
tensor([[-15930.3672, -19061.7109, -11311.1113],
        [  -103.9146,  -2637.3850,  -1170.5750]])


In [150]:
print(b)
print(b.grad)

tensor([-0.4001, -1.0923], requires_grad=True)
tensor([-193.5156,   -7.9926])


### GRADIENT DESCENT

In [151]:
'''w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)'''

'w.grad.zero_()\nb.grad.zero_()\nprint(w.grad)\nprint(b.grad)'

In [152]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [153]:
print(w)
print(b)

tensor([[ 0.3616, -1.4129,  0.1732],
        [ 1.9154, -0.6857, -0.2737]], requires_grad=True)
tensor([-0.3982, -1.0922], requires_grad=True)


In [154]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(17865.3203, grad_fn=<DivBackward0>)


In [155]:
for i in range(2000):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5  #1e-5 is learning rate
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [156]:
#calculate loss
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(1.7165, grad_fn=<DivBackward0>)


In [157]:
preds

tensor([[ 57.0760,  70.2541],
        [ 82.4335,  99.6973],
        [118.3198, 135.2558],
        [ 20.9827,  37.6741],
        [102.2931, 116.8435]], grad_fn=<AddBackward0>)

In [158]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

### Linear regression using PYTORCH

In [159]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [187]:
from torch.utils.data import TensorDataset
#define dataset
train=TensorDataset(inputs,targets)
print(train[0:3])
print(train[[1,3,4,5,6]])

(tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]]))
(tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.]]), tensor([[ 81., 101.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.]]))


In [188]:
from torch.utils.data import DataLoader
batch_size=5
train_dl=DataLoader(train,batch_size,shuffle=True)

In [198]:
for xb,yb in train_dl:
  print(xb)
  print(yb)

tensor([[ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 91.,  87.,  65.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.]])
tensor([[ 81., 101.],
        [103., 119.],
        [ 80., 102.],
        [118., 134.],
        [ 20.,  38.]])
tensor([[ 68.,  97.,  70.],
        [101.,  44.,  37.],
        [ 92.,  87.,  64.],
        [ 74.,  66.,  43.],
        [ 73.,  66.,  44.]])
tensor([[102., 120.],
        [ 21.,  38.],
        [ 82., 100.],
        [ 57.,  69.],
        [ 57.,  69.]])
tensor([[102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 88., 134.,  59.],
        [ 68.,  96.,  71.],
        [ 73.,  67.,  43.]])
tensor([[ 22.,  37.],
        [119., 133.],
        [118., 132.],
        [104., 118.],
        [ 56.,  70.]])


In [199]:
import torch.nn as nn
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1562, -0.2758,  0.3033],
        [-0.0428, -0.3808,  0.0447]], requires_grad=True)
Parameter containing:
tensor([-0.1171, -0.0224], requires_grad=True)


In [200]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1562, -0.2758,  0.3033],
         [-0.0428, -0.3808,  0.0447]], requires_grad=True),
 Parameter containing:
 tensor([-0.1171, -0.0224], requires_grad=True)]

In [201]:
preds=model(inputs)
preds

tensor([[  5.8472, -26.7390],
        [  9.2358, -34.5676],
        [ -5.8930, -52.1810],
        [ 15.1742, -19.1098],
        [  5.4139, -36.4037],
        [  6.2791, -26.4010],
        [  9.8148, -34.1421],
        [ -5.4335, -52.1792],
        [ 14.7423, -19.4478],
        [  5.5610, -36.3162],
        [  6.4262, -26.3135],
        [  9.6677, -34.2296],
        [ -6.4720, -52.6065],
        [ 15.0271, -19.1974],
        [  4.9820, -36.7417]], grad_fn=<AddmmBackward>)

In [202]:
import torch.nn.functional as f #For loss function
loss_fn=f.mse_loss
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(12192.6787, grad_fn=<MseLossBackward>)


In [203]:
?nn.Linear #FOR HELP for a function

In [204]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5) #SGD-Stochastic Gradient Descent

Train The Model

In [216]:
#Utility function to train the model
def fit(num_epochs,model,loss_fn,opt):
  for epoch in range(num_epochs):
    #Train Batches xb,yb
    for xb,yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if(epoch+1)%100==0:
      print('Epoch ',epoch+1,"/",num_epochs," Loss: {:.4f}".format(loss.item()))

In [219]:
fit(500,model,loss_fn,opt)

Epoch  100 / 500  Loss: 1.1538
Epoch  200 / 500  Loss: 0.7927
Epoch  300 / 500  Loss: 1.2483
Epoch  400 / 500  Loss: 0.9213
Epoch  500 / 500  Loss: 1.3437


In [222]:
preds=model(inputs)
preds

tensor([[ 56.8979,  70.4091],
        [ 82.0071, 100.5668],
        [118.1319, 132.8184],
        [ 20.7853,  37.7771],
        [101.8276, 118.5234],
        [ 55.6524,  69.3312],
        [ 81.8659, 100.6634],
        [118.4283, 133.4215],
        [ 22.0308,  38.8550],
        [102.9318, 119.6979],
        [ 56.7567,  70.5057],
        [ 80.7617,  99.4888],
        [118.2731, 132.7218],
        [ 19.6811,  36.6026],
        [103.0730, 119.6013]], grad_fn=<AddmmBackward>)

In [221]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])